# Generated by Django 5.2.4 on 2025-09-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_borroweditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='borrowing_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='borrowing_qr_codes/'),
        ),
    ]
