# Generated by Django 5.2.4 on 2025-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplyrequest_borrowing_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='return_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
