# Generated by Django 5.2.6 on 2025-12-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_analytics_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='inventory_u_user_id_d0de62_idx',
            old_name='inventory_u_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='inventory_u_activit_98cd15_idx',
            old_name='inventory_u_activity_timestamp_idx',
        ),
    ]
