# Generated by Django 5.2.6 on 2025-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_inventory_u_user_id_timestamp_idx_inventory_u_user_id_d0de62_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycategory',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Mark category as materials (e.g., tables, chairs) so they can be borrowed as equipment'),
        ),
    ]
