# Generated by Django 5.2.6 on 2025-12-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplycategory_is_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='requested_location',
            field=models.CharField(blank=True, help_text='Location where the requester intends to use the equipment', max_length=200, null=True),
        ),
    ]
