# Generated by Django 5.2.6 on 2026-01-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID for grouping multiple requests created in one batch', max_length=50, null=True),
        ),
    ]
