# Generated by Django 5.2.6 on 2026-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_supplyrequest_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
