# Generated by Django 5.2.6 on 2026-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_inventorytransaction_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplyrequest",
            name="group_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="supply",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product image or photo",
                null=True,
                upload_to="supply_images/",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supply",
            name="min_stock_level",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
