# Generated by Django 5.2.6 on 2026-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total purchase amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="date_purchased",
            field=models.DateField(
                blank=True, help_text="Date when the item was purchased", null=True
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Serial number or code for tracking",
                max_length=100,
                null=True,
            ),
        ),
    ]
