# Generated by Django 5.2.6 on 2026-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_supply_amount_supply_date_purchased_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("in", "Stock In"),
                    ("out", "Stock Out"),
                    ("adjustment", "Adjustment"),
                    ("lost", "Lost Item"),
                    ("damaged", "Damaged Item"),
                ],
                max_length=20,
            ),
        ),
    ]
